# Generated by Django 4.1.3 on 2022-12-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_alter_employee_curr_status_alter_mcp_curr_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='mission',
        ),
        migrations.AddField(
            model_name='employee',
            name='mission',
            field=models.ManyToManyField(blank=True, default=None, to='src.mission'),
        ),
    ]
